// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb3mPHdOvRB5Iryxph2j3NpAVeQrHRW-g',
    appId: '1:476129077955:web:40520e8700fb2cc2bc1076',
    messagingSenderId: '476129077955',
    projectId: 'messageboardapp-8525a',
    authDomain: 'messageboardapp-8525a.firebaseapp.com',
    storageBucket: 'messageboardapp-8525a.firebasestorage.app',
    measurementId: 'G-RXRV7W7GW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABg0B8dINBGXzw-bruGLkkC5LHsnR_DLc',
    appId: '1:476129077955:android:636e4a0bf36e3656bc1076',
    messagingSenderId: '476129077955',
    projectId: 'messageboardapp-8525a',
    storageBucket: 'messageboardapp-8525a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWPbtNBYQPFRBfhOnMgEZtezSWQlGgt7A',
    appId: '1:476129077955:ios:aa6f0bb6c64e51d1bc1076',
    messagingSenderId: '476129077955',
    projectId: 'messageboardapp-8525a',
    storageBucket: 'messageboardapp-8525a.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWPbtNBYQPFRBfhOnMgEZtezSWQlGgt7A',
    appId: '1:476129077955:ios:aa6f0bb6c64e51d1bc1076',
    messagingSenderId: '476129077955',
    projectId: 'messageboardapp-8525a',
    storageBucket: 'messageboardapp-8525a.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb3mPHdOvRB5Iryxph2j3NpAVeQrHRW-g',
    appId: '1:476129077955:web:3fd3ef2c7dcbc548bc1076',
    messagingSenderId: '476129077955',
    projectId: 'messageboardapp-8525a',
    authDomain: 'messageboardapp-8525a.firebaseapp.com',
    storageBucket: 'messageboardapp-8525a.firebasestorage.app',
    measurementId: 'G-ZY6X0P90K9',
  );
}
